googleapis/google-api-nodejs-client

.travis.yml

More info:
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
Travis now uses Docker-based infrastructure which is more efficient and much faster. Let's upgrade (since we do not need any of the features currently limited to the old VM infra, like `sudo`)!

Use the new Travis infrastructure

---

package.json

Tests are OK, API regeneration successful.
Closes #341.

Update request to 2.51

---

test/test.drive.v2.js

Do not output stuff to console during testing

---

lib/auth/oauth2client.js

Doc was copied from previous property.

oauth2client.ISSUER_ documentation fix

---

package.json

Changelog from 2.54.0 : https://github.com/request/request/blob/master/CHANGELOG.md

Update "requests" to 2.58.0

---

.travis.yml
package.json

Async from 0.9.0 to 1.4.1 [Changelog](https://github.com/caolan/async/blob/master/CHANGELOG.md) - bug fixes and new features, no breaking changes
Request from 2.58.0 to 2.60.0 [Changelog](https://github.com/request/request/blob/master/CHANGELOG.md) - bug fixes
Thanks !

Update async & request

---

lib/googleapis.js

Nobody seems to care about linting error.
Maybe they are busy doing more meaningful stuff.
Let me fix the linting for you then.

fix linting error

---

lib/generator.js

Sometimes, all you have is a file-based discovery doc. This PR makes those times easier to cope with.

Added support for building an API from a file.

---

.github/PULL_REQUEST_TEMPLATE.md

This pull request removes extra characters from the pull request template

[github template] minor edits to pull request template

---

README.md

This is a simple fix to the readme
- [ x ] Approprate changes to readme/docs are included in PR

v2 does not have the create function, updating to v3

---

CHANGELOG.md
apis/bigquery/v2.js
apis/compute/v1.js
apis/deploymentmanager/v2.js
apis/pubsub/v1.js
apis/storage/v1.js
lib/generator.js
package.json
templates/method-partial.js

Updates the generator to pull in auto-generated code samples.

Pull in auto-generated samples.

---

samples/README.md
samples/youtube/README.md
samples/youtube/upload.js

Add YouTube video upload sample

---

README.md

Docs: pass parameters to redirect URIs

---

README.md

README: s/gcloud/google-cloud/

---

README.md

Add notice on library maintenance

---

templates/api-endpoint.ts
templates/method-partial.ts
templates/resource-partial.ts

Make the generator deterministic

---

package.json

Updated node version in package.json

---

.travis.yml

Added check for Node v8 in travis ci

Update .travis.yml for Node 8 support

---

tsconfig.json

Generate typescript declaration files.

Generate declaration files

---

.gitignore
package.json
yarn.lock

fix: make clean work on windows

---

samples/drive/list.js
samples/people/me.js
test/test.discover.ts

Replace assertion with console warning for discovery

---

lib/apirequest.ts
lib/discovery.ts
lib/googleapis.ts
scripts/generate.ts
scripts/generator.ts
scripts/generator_utils.ts
test/test.auth.ts
test/test.clients.ts
test/test.discover.ts
test/test.drive.v2.ts
test/test.media.ts
test/test.options.ts
test/test.path.ts
test/test.urlshortener.v1.ts

More `gts fix` changes. Should all be cosmetic.

chore: improve code style

---

package.json

Playing Greenkeeper's role here.

update source-map-support to 0.5.2

---

.circleci/config.yml

run npm install before npm publish

run npm install before npm publish

---

README.md

docs: update readme to reflect new api

---

package.json

Addresses #955.  We should really land #956 first just to make sure I didn't break anything.

fix: add files section to package.json

---

src/lib/apirequest.ts
src/lib/discovery.ts
test/test.apikey.ts
test/test.auth.ts
test/test.path.ts
tsconfig.json

chore: improve typing and build

---

src/lib/apirequest.ts
src/lib/discovery.ts
src/lib/endpoint.ts
src/lib/googleapis.ts
test/test.apikey.ts
test/test.drive.v2.ts
test/test.options.ts
test/utils.ts

Inching towards noImplicitAny.

chore: improve typing

---

package-lock.json
package.json
src/lib/api.ts
src/lib/apirequest.ts
src/lib/endpoint.ts
src/lib/googleapis.ts
test/test.options.ts

fix: move pify to deps

---

src/lib/apirequest.ts
test/test.media.ts

fix: raise default of maxContentLength

---

.gitignore
package-lock.json
package.json
samples/sheets/quickstart.js

We're seeing a bunch of reports of old docs from codesite.  This is the first step to fixing #999.   We will need to follow up with tests, and then submit a CL to embed the code snippet.

docs: add the sheets quickstart

---

src/apis/index.ts
src/lib/api.ts
src/lib/discovery.ts
src/lib/googleapis.ts
src/templates/index.njk
test/samples/test.samples.drive.ts
test/samples/test.samples.gmail.ts
test/samples/test.samples.youtube.ts
test/test.media.ts
test/test.options.ts
tsconfig.json

There's still a lot of work to do here, but at least this way we won't leak more `any` into the wild :) Resolves #880

chore: enable noImplicitAny

---

package-lock.json
samples/analytics/analytics.js
samples/blogger/blogger.js
samples/compute/compute.js
samples/customsearch/customsearch.js
samples/defaultauth.js
samples/drive/upload.js
samples/jwt.js
samples/mediaupload.js
samples/mirror/mirror.js
samples/oauth2.js
samples/people/me.js
samples/urlshortener/urlshortener.js
samples/youtube/search.js
test/samples/test.samples.auth.ts
test/samples/test.samples.customsearch.ts
test/samples/test.samples.drive.ts

fix: repair a bunch of samples

---

samples/gmail/watch.js
test/samples/test.samples.gmail.ts

feat: add gmail watch sample

---

package-lock.json
samples/drive/download.js
test/samples/test.samples.drive.ts

fix: fix download sample

---

samples/gmail/send.js
test/samples/test.samples.gmail.ts

feat: add a gmail send sample

---

README.md

The readme was a little wrong in a few places.  Updating it to make the return parameters completely clear.  Resolves #1064.

docs: improve the readme

---

package-lock.json
samples/analyticsReporting/batchGet.js
test/samples/test.samples.analyticsReporting.ts

feat: add analytics reporting sample

---

package-lock.json
samples/webmasters/query.js
src/lib/apirequest.ts
test/samples/test.samples.webmasters.ts
test/test.path.ts

fix: encodeURIComponent path params

---

.circleci/config.yml
package.json

Release notes in https://github.com/google/google-api-nodejs-client/releases/tag/untagged-d6a7022405184a1e8921

chore: release 28.0.1

---

README.md
test/fixtures/kitchen/src/index.ts

docs: fix sample to be typescript friendly

---

src/apis/androidmanagement/v1.ts
src/apis/androidpublisher/v2.ts
src/apis/doubleclicksearch/v2.ts
src/apis/firebasedynamiclinks/v1.ts
src/apis/iam/v1.ts
src/apis/index.ts
src/apis/partners/v2.ts
src/apis/safebrowsing/v4.ts
src/apis/serviceconsumermanagement/v1.ts
src/apis/servicemanagement/v1.ts
src/apis/serviceusage/v1beta1.ts
src/apis/serviceuser/v1.ts
src/apis/sheets/v4.ts
src/apis/slides/v1.ts
src/apis/texttospeech/v1beta1.ts
src/apis/videointelligence/v1beta1.ts

Just a regular regen before publishing new release.

chore: regenerating all APIs

---

.github/CONTRIBUTING.md
README.md
package-lock.json
samples/defaultauth.js
samples/jwt.js
samples/mirror/mirror.js
test/fixtures/service.json
test/samples/test.samples.auth.ts

This should make the README *a lot* easier to navigate an understand. 
Resolves #713 
Resolves #1035

docs: improve the readme and samples

---

samples/README.md

docs: fix links to ref docs

---

samples/plus/post.js
test/samples/test.samples.plus.ts

feat: add google plus post sample

---

README.md

Read the sentence aloud.
Also fixes:
- Capitalization
- Period

Fix StackOverflow sentence.

---

samples/youtube/search.js

Fixes the youtube search sample code.

Fix sample for youtube search

---

package.json

There are a few fixes burnin a hole in my pocket here.  
Release notes here:
https://github.com/google/google-api-nodejs-client/releases/edit/untagged-c744e047a3d5b2ffd755

chore: release 29.0.0

---

README.md

Minor fix to README. I think an issue would be overkill :)

README: Fix broken link to issue tracker

---

README.md

docs: remove caveat about TypeScript docs

---

package-lock.json
samples/urlshortener/urlshortener.js
src/lib/apirequest.ts

Plus a bonus sample fix. Resolves #1159

fix: use reject handler instead of catch for callbacks

---

package.json

[Release notes](https://github.com/google/google-api-nodejs-client/releases/edit/untagged-ae526cbb7d184f1a2ec5).

chore: release 31.0.0

---

.circleci/config.yml

fix: cd before publishing

---

.circleci/config.yml
package.json

This is a struggle over here.  I yanked the googleapis-common stuff until we could figure this out. 
[Release notes](https://github.com/google/google-api-nodejs-client/releases/edit/untagged-a57a31b23314f60998a1)

chore: release 31.0.2

---

samples/analytics/analytics.js

Just a small comment clarification 😄

analytics.js typo fix

---

README.md

docs: fix samples link in README.md

---

package.json

[Release notes](https://github.com/google/google-api-nodejs-client/releases/edit/untagged-c4f2f4bd006a2bd10d3c)

chore: release 32.0.0

---

README.md

docs: do not reccomend refreshAccessToken() method

---

package.json

[Release notes](https://github.com/google/google-api-nodejs-client/releases/edit/untagged-335ab15c71b2bec7e6ea) here!

chore: release v33.0.0

---

.circleci/npm-install-retry.js

If this works, I will swing the synth hammer to make the update broadly.

Make npm install timeout configurable

---

.github/CONTRIBUTING.md

docs: fix generator script path

---

CHANGELOG.md
package.json
samples/package.json

Release googleapis v34.0.0

---

CHANGELOG.md
package.json
samples/package.json

Release googleapis v35.0.0

---

samples/drive/README.md

add note about minimum Node.js version required to run drive samples to README.md

---

CHANGELOG.md
package.json
samples/package.json

Release googleapis v36.0.0

---

README.md

docs: Fixes typo on readme.md

---

CHANGELOG.md
package.json
samples/package.json

Release googleapis v37.0.0

---

CHANGELOG.md
package.json
samples/package.json

Release googleapis v37.1.0

---

CHANGELOG.md
package.json
samples/package.json

Release googleapis v37.2.0

---

src/generator/templates/api-endpoint.njk
src/generator/templates/resource-partial.njk

fix: correct types param name for media mime-type

---

CHANGELOG.md
package.json
samples/package.json

Release googleapis v38.0.0

---

README.md
samples/drive/README.md

Fix typos in README.md and samples/drive/README.md. 
Documenation to Documentation and requared to required, respectively.

Fix typos in Readmes

---

README.md

Fix typo error. 'The' -> 'There'

docs: Update typo in README.md

---

CHANGELOG.md
package.json
samples/package.json

Release googleapis v39.0.0

---

CHANGELOG.md
package.json
samples/package.json

Release googleapis v39.2.0

---

package.json

https://github.com/googleapis/nodejs-googleapis-common/releases/tag/v2.0.2

fix(deps): explicitly update google-apis-common to latest

---

README.md

- [✔️] Tests and linter pass
- [✔️] Code coverage does not decrease (if any source code was changed)
- [✔️] Appropriate docs were updated (if necessary)

docs: fixes options section anchor link

---

samples/docs/create.js
samples/docs/get.js
test/samples/test.samples.docs.ts

docs(samples): add google docs samples

---

samples/sampleclient.js

Adds region tags to allow sample app to be tracked.

docs(samples): adds region tags to sampleclient

---

package.json

https://github.com/googleapis/google-cloud-node/issues/2972

chore(dep)!: deprecate node 8

---

package.json
system-test/kitchen.test.ts
test/fixtures/kitchen/package.json
test/fixtures/kitchen/tsconfig.json

I noticed the kitchen tests were busted on an unrelated PR :)

test: update kitchen test tsc

---

package.json
src/generator/download.ts
src/generator/generate.ts
src/generator/generator.ts
src/generator/synth.ts
test/test.synth.ts

This continues the slow build towards per-API PRs.  Not hooked up quite yet.

build: add changelog generation

---

src/generator/synth.ts

I'm like 17% sure this one is it

build: improve logs, slice PR messages

---

README.md

docs: improve auth docs in the readme

---

README.md
src/generator/synth.ts

docs: update broken link on README
