googleapis/google-api-nodejs-client

lib/transporters.js
test/test.transporters.js

Hopefully I have not missed any other place where we wrap callbacks or create errors ourselves...
Thanks to @sindresorhus for pointing the issue out!
Closes #345

All API call errors should be returned as instances of Error

---

lib/transporters.js
test/test.transporters.js

This adds better support for errors returned from google apis that follow this response body format:
```
{
error: 'invalid_grant',
error_description: 'Code was already redeemed.'
}
```
(in this example, for `oauth2.tokeninfo(...)`)
Previously, stack trace message for this error would look like:
```
Error
at Request._callback (/Users/stephen/git/formresponses/node_modules/googleapis/lib/transporters.js:78:13)
at Request.self.callback (/Users/stephen/git/formresponses/node_modules/request/request.js:373:22)
at Request.EventEmitter.emit (events.js:110:17)
at Request.<anonymous> (/Users/stephen/git/formresponses/node_modules/request/request.js:1318:14)
at Request.EventEmitter.emit (events.js:129:20)
...
```
With this change, they would look like:
```
Error: Code was already redeemed.
at …
```

Add better handling for string errors

---

test/test.oauth2.js

Sometimes the tests ran so fast that a race condition would occur and this test would fail. Added some equalities to help it out.

Race condition in expiry date test

---

lib/transporters.js
test/test.transporters.js

Handle 500 errors that include an error message.

---

lib/utils.js
test/test.utils.js

The lack of a `hasOwnProperty` check can accidentally cause functions on the prototype to bubble up to being a parameter in an API request.
For example... defining a polyfill:
```
Object.prototype.entries = function* entries(obj) {
for (let key of Object.keys(obj)) {
yield [key, obj[key]];
}
};
```
will cause an extra `entries` param to exist in a request in the query string, e.g. `https://www.googleapis.com:443'/calendar/v3/calendars/stephen%40stephenwan.net/events?entries=`.

Change extend util to check hasOwnProperty

---

lib/googleapis.js
package.json
test/test.auth.js

When the refactoring happened to pull the auth module out of the V1 library and into it's own separate auth library, a critical piece was left out. This PR actually exposes the default auth module into the V1 client.

Actually expose the default auth module

---

CONTRIBUTING.md
lib/generator.js
templates/method-partial.js

Fixes Pubsub and other endpoints that use a different baseUrl.

Fix endpoints for APIs by using baseUrl

---

MIGRATING.md

Seemed to be a typo pointing the google-api-nodejs-client instead of the correct location.

Fix link to the googleauth library

---

examples/defaultauth.js

`res` is not a variable in this callback

bugfix: replacing res.send with console.log

---

README.md

When I first came across the example in the Readme, I tried blindly copy/pasting it into a new sample js file and was surprised to see it failed with the following error:
`TypeError: Cannot read property 'longUrl' of null`
I was just about to submit a bug report, but I realized after adding an error check to the sample code that it was failing because no authorization credentials were provided.

Handle error in URL shortener example

---

README.md

I'm guessing that when this documentation was first written, either the Google Developer Console didn't yet provide .json files or the JWT auth client didn't yet accept keys as strings. Now that they do, it's much easier to configure the client using the .json file than it is to convert a .p12 file to .pem file. Also, the instructions for using openssl to convert a .p12 file didn't work on my system and I had to search for the correct way to do that. So, I removed the convert .p12 to .pem instructions and example and replaced them with an example using a .json file. I also added a link to the example/jwt.js in case someone wants to still use .pem files, use the impersonate functionality or any of the other functionality.

Example using JWT auth client with .json files

---

lib/apirequest.js
test/test.path.js

GAPI node.js client currently url-encodes path parameters. This causes problem when path parameters contain '/'. This pull request stops url encoding path parameters. This makes node.js client consistent with GAPI Go client.

Avoid url-encoding path parameters.

---

apis/compute/v1.js
apis/deploymentmanager/v2beta1.js
apis/deploymentmanager/v2beta2.js
apis/dns/v1.js
apis/dns/v1beta1.js
apis/genomics/v1.js
apis/pubsub/v1.js
apis/pubsub/v1beta2.js
lib/apirequest.js
lib/generator.js
package.json
templates/method-partial.js
test/test.query.js

Simple escape mechanism to allow parameter names that happen to conflict with names the client library uses. Appends "_" to parameters that would otherwise conflict. Currently only a few APIs exhibit this issue, notably cloud APIs with the 'resource' parameter.

Avoid parameter name conflicts with resource/media/auth

---

README.md

This example never defines the compute service

Fix compute ADC example

---

AUTHORS
CONTRIBUTORS
README.md
jsdoc-conf.json
package.json

* Upgraded dependencies
* Fixed `jsdoc-conf.json` so it succeeds (tutorials will have to be added later, it can't parse the `examples/` directory). Should be able to publish `gh-pages` now.
* Added a Table of Contents to README.md
* Added `AUTHORS` and `CONTRIBUTORS` files

General cleanup.

---

lib/apirequest.js
package.json
samples/README.md
samples/youtube/README.md
samples/youtube/playlist.js
samples/youtube/search.js
test/test.transporters.js

Fixes #414 - This adds etag support by allowing consumers to append their own HTTP headers to the request.  It also shows how to read details from the resulting HTTP response.

add etag support with samples and test

---

scripts/generate.js

scripts/generate.js attempts to parse all arguments as api urls.  This breaks the existing functionality of being able to provide a `--discovery-url` flag.  This patch restores this functionality while keeping the new behavior of generating apis for each un-named argument.
```
➜  google-api-nodejs-client git:(master) node scripts/generate --discovery-url "https://my.discovery.json" 
/Users/phaedrus/reference/javascript/google-api-nodejs-client/scripts/generate.js:33
throw err;
^
Error: Invalid URI "--discovery-url"
```
An issue still exists where the apis generated will not be included in apis/index.js, as this file is generated from the discovery url file.

Restore --discovery-url functionality to scripts/generate

---

README.md

Fixes #544
Replace deprecated method insert with create for Drive API v3.
Replace title (deprecated in v3) with name param for v3.

Update documentation for Drive API v3

---

lib/apirequest.js
lib/generator.js
lib/googleapis.js
package.json
test/test.apikey.js
test/test.auth.js
test/test.clients.js
test/test.discover.js
test/test.drive.v2.js
test/test.media.js
test/test.options.js
test/test.path.js
test/test.query.js
test/test.transporters.js
test/test.urlshortener.v1.js
test/utils.js

Addresses:
- #416
What this PR adds:
Let's say that the latest `googleapis` in NPM supports `someapi` `v1`, you would do:
```js
var google = require('googleapis');
var someapi = google.someapi('v1');
```
But, what if `v2` of `someapi` is available, but the discovery doc isn't available in the main discovery index yet, or maybe it is and a new release of `googleapis` hasn't been generated yet. You can now do this:
```js
var google = require('googleapis');
google.load('http://domain.com/path/to/someapi/v2/discovery.json', function (err, someapi) {
// use someapi
});
```
It also works for Cloud Endpoints v1:
```js
var google = require('googleapis');
google.discover('https://myapp.appspot.com/_ah/api/discovery/v1/apis', function (err, apis) {
var myapi = google.myapi('v3');
// use myapi
}); …
```

Added "load" method for discovering an API at runtime.

---

scripts/generate.js

Fixes #566
- [X ] `npm test` succeeds
- [ X] Pull request has been squashed into 1 commit
- [ X] I did NOT manually make changes to anything in `apis/`
- [ X] Code coverage does not decrease (if any source code was changed)
- [ X] Appropriate JSDoc comments were updated in source code (if applicable)
- [ X] Approprate changes to readme/docs are included in PR
The `process.exit` replaced a `return`that was failing a lint check, but ended up causing the generator to quit before the generation was complete.

Replace process.exit with an else block

---

apis/datastore/v1beta3.js
apis/proximitybeacon/v1beta1.js
apis/runtimeconfig/v1beta1.js
apis/sheets/v4.js
apis/youtubeAnalytics/v1.js
apis/youtubeAnalytics/v1beta1.js

Re-generating API classes.

---

package.json

Fixes #608.
`tough-cookie`, a transitive dependency of this module via `request`, has a security vulnerability:
https://nodesecurity.io/advisories/130
`request` has already upgraded its dependency to fix the issue, so it's just a matter of bumping the version depended on here.

Upgrade request dependency, fixes #608

---

README.md
templates/api-endpoint.js
templates/method-partial.js
test/test.options.js

Fixes #501
Fixes #618
Fixes #621 
```js
drive.files.export({
fileId: 'asxKJod9s79', // A Google Doc
mimeType: 'application/pdf',
encoding: null // This is ignored
}, , function (err, buffer) {
// Oh no! buffer got incorrectly interpreted as a string!
});
```
```js
drive.files.export({
fileId: 'asxKJod9s79', // A Google Doc
mimeType: 'application/pdf'
}, {
encoding: null // Make sure we get the binary data
}, function (err, buffer) {
// Nice, the buffer is actually a Buffer!
});
```

Add support for overriding request options.

---

README.md

Currently the documentation does not indicate what a what an auth scope looks like for JWT authentication. It currently uses the non-descriptive `[scope1, scope2]`.
Instead, I propose to be more explicit, and write out the auth scope URLS:
`['https://www.googleapis.com/auth/plus.me', 'https://www.googleapis.com/auth/calendar']`
Lastly, to give readers more context on what these urls are, I added a descriptive comment afterwards:
`['https://www.googleapis.com/auth/plus.me', 'https://www.googleapis.com/auth/calendar'] // an array of auth scopes`
This also follows the other documentation, for example [Generating an Authentication URL](https://github.com/google/google-api-nodejs-client#generating-an-authentication-url), where auth scopes are explicitly stated.

Make it clearer what a JWT auth scope looks like.

---

lib/apirequest.ts
test/test.query.ts

This commit addresses two issues concerning falsy param values:
1. User confusion
Given a method with a required parameter `foo`, if a request is made
with the following object:
```
{
foo: 0
}
```
The following error is returned:
```Error: Missing required parameters: foo```
This message is confusing - it's not obvious that the issue is that
`foo` cannot be zero. This commit allows the above request to pass to
the server, with the expectation that the server returns a more
appropriate error message.
The alternative solution, writing a special error message stating
that falsy values are not allowed for required parameters, is
complicated because of the second issue (below).
2. Required boolean params
The `compute:v1` API contains a method,
`compute.instances.setDiskAutoDelete`, which has a …

Allow falsy params

---

templates/method-partial.ts
test/test.options.ts

This can be useful for testing (pointing clients at `localhost`) or proxying (if for some reason the `proxy` option is insufficient).
Note that I am still using `buildurl`, though I am only building url fragments. Perhaps it should be renamed to `escapeurl`, as it doesn't even really build a url...
I did not squash so you could see the template changes vs the generated api code changes. Let me know if you want me to do so.

Allow specifying rootUrl at runtime

---

README.md

I almost lost my mind trying to understand why `refresh_tokens` weren't in my response until I find https://github.com/google/google-api-nodejs-client/issues/750#issuecomment-304521450.
This PR tries to make this more obvious at README.

Important note about refresh_token

---

README.md

Service Tokens are the solution to use when using Service accounts. Adding the string 'service account' will help people performing a text search on our README

Adding the 'Service account' keyword

---

README.md

Hi everyone!
The `state` parameter in the auth URL should be a string, as documented here https://developers.google.com/identity/protocols/OAuth2WebServer .
In this README was stated that is possible to pass the `state` as an object literal, but this doesn't work. Changing the parameter to a string works like expected.
Fixes #794 #716

Fix wrong documentation for generateAuthUrl()

---

lib/apirequest.ts
lib/discovery.ts
package.json
scripts/generator.ts
scripts/generator_utils.ts
test/test.apikey.ts
test/test.auth.ts
test/test.options.ts
test/test.query.ts

Fixes #816 
Upgraded google-auth-library to v0.11.0 and fixed some bugs that were related to the switch to typescript, eg. no setCredentials anymore in favor of getters/setters
- [ x ] `npm test` succeeds
- [ x ] Pull request has been squashed into 1 commit
- [ x ] I did NOT manually make changes to anything in `apis/`
- [ x ] Code coverage does not decrease (if any source code was changed)
- [ x ] Appropriate JSDoc comments were updated in source code (if applicable)
- [ x ] Approprate changes to readme/docs are included in PR

Upgrade google-auth-library to v0.11.0 and fix regressions / bugs

---

README.md

Because the `resource` parameter is only briefly mentioned in the README.md, it's
an immensely useful feature that's difficult to track down outside of the code base.
Until better messaging can be provided---the current "Error: No label add or removes
specified" could use some DX love---this example highlights the `resource` parameter
as a feature of this API.
Addresses Issue #808

Highlights the `resource` Parameter

---

MIGRATING.md
README.md
package-lock.json
package.json
src/lib/apirequest.ts
src/lib/discovery.ts
src/lib/googleapis.ts
src/scripts/generator.ts
src/scripts/generator_utils.ts
test/test.apikey.ts
test/test.auth.ts
test/test.clients.ts
test/test.drive.v2.ts
test/test.media.ts
test/test.options.ts
test/test.path.ts
test/test.query.ts
test/test.transporters.ts
test/test.urlshortener.v1.ts
test/utils.ts

The latest version of the google-auth-library makes a few breaking changes. 
Note - this is ready!  Please take another look if interested :)

Upgrade to the latest google-auth-library

---

.circleci/config.yml

Node 7 never hit LTS, and all of those users should be using 8. Lets drop it from the CI :)

chore: remove node 7 from CI

---

package-lock.json
package.json
test/test.auth.ts

This upgrades us to the 1.1.0 release of the google-auth-library.  There were multiple changes in that release that were breaking our CI (even though they were probably not semver major changes).

chore: upgrade to the latest google-auth-library and fix the build

---

package-lock.json
package.json
test/fixtures/kitchen/package.json
test/fixtures/kitchen/src/index.ts
test/fixtures/kitchen/tsconfig.json
test/test.kitchen.ts

Adds a test to ensure our `d.ts` generation is actually working and usable.  Addresses #956.

test: add test for typescript d.ts

---

test/test.kitchen.ts

Windows builds fail being unable to run `npm` using `childprocess.spawn`. Details [here](https://github.com/nodejs/node/issues/3675). As a quick solution, passing `{ shell: true }` to `spawn` helps (I guess it's OK for the test code).

try some appveyor magic

---

.npmignore

Now that we define `files` in package.json, we don't need to have an explicit npmignore.

chore: remove .npmignore

---

package-lock.json
package.json
src/lib/discovery.ts
src/lib/googleapis.ts
test/test.apikey.ts
test/test.auth.ts
test/test.clients.ts
test/test.discover.ts
test/test.drive.v2.ts
test/test.media.ts
test/test.options.ts
test/test.path.ts
test/test.query.ts
test/test.transporters.ts
test/test.urlshortener.v1.ts
test/utils.ts

This change does a few things:
- Eliminates the `async` and `power-assert` npm depdendencies
- Introduces a few async APIs in the generator
- Basic cleanup
One step closer to noImplicitAny.

chore: make a few APIs async

---

package.json

We messed up the last release :(  Resolves #988. 
Draft release notes are here:
https://github.com/google/google-api-nodejs-client/releases/edit/untagged-6c5a57ab1bbce712f6a8

chore: release 26.0.1

---

package.json

Releasing new APIs as v27.0.0.
---
This release contains updates to various APIs and various fixes. 
- chat v1
- genomics v2alpha1
- serviceusage v1
- vision v1p2beta1
- firebaseremoteconfig v1
- (#1016) raise default of maxContentLength
- (#1020) treat 304 responses as success
- (#1010) move pify to deps (resolves #1007)
---

chore: release v27.0.0

---

src/lib/apirequest.ts
test/test.auth.ts
test/test.transporters.ts

feat: request gzip responses

---

.circleci/config.yml
.circleci/get_workflow_name.py

Pretty much the same change I applied to all Veneer libraries, but with some specifics (requiring token to access API; the token is set in CircleCI environment).

chore: setup nightly builds workflow

---

package.json

Aw snap, it's time to ship.  Release notes drafted here:
https://github.com/google/google-api-nodejs-client/releases/edit/untagged-0f47865addddcee903ba

chore: release 28.0.0

---

package-lock.json
package.json

Releasing minor update 28.0.1. Release notes draft is [here](https://github.com/google/google-api-nodejs-client/releases/tag/untagged-957f1f7620f059548285).

chore: release 28.1.0 and update dependencies

---

README.md

docs: explain how to use a refresh_token

---

.circleci/config.yml
package.json

Now that node.js 4 is EOL, I would like to explicitly drop support for it here.  Thoughts / opinions welcomed :)

fix: drop support for node.js 4

---

README.md

Small docs update to specify an optional method to use for refreshing the access token.
Additional fix for #1157 
- [n/a] Code coverage does not decrease (if any source code was changed)
- [n/a] Appropriate JSDoc comments were updated in source code (if applicable)

Specifies method for refreshing access token

---

package.json
src/shared/package.json

[Release notes](https://github.com/google/google-api-nodejs-client/releases/edit/untagged-da14cc88a5cb369b7758)

chore: release 31.0.1

---

package-lock.json
samples/sampleclient.js

fix: cannot read property of undefined in sampleclient.js line 42
Added: line 32. All tests passed.
```
const keyFile = require(keyPath);
keys = keyFile.installed || keyFile.web;
```
oauth2.keys.json when downloaded looks like this:
{"installed":{
"client_id":"",
"project_id": "",
...
"redirect_uris":[...]}
}
It's also mentioned here: https://github.com/gsuitedevs/node-samples/blob/master/drive/quickstart/index.js

 fix: cannot read property of undefined. sampleclient.js line 42

---

samples/drive/README.md
samples/drive/quickstart.js

fix: consistent use of keyfile name

---

package.json

Mostly moves out dependencies that are brought in by googleapis/nodejs-googleapis-common now.

chore: reduce # of dependencies

---

README.md
package.json
samples/README.md

Generating docs with TypeDoc is currently busted.  Having out of date docs is worse than no API reference docs, so I want to take them down while we work out another solution.

Remove reference docs

---

samples/analyticsReporting/batchGet.js

Fix error handling in batchGet sample

---

README.md

Some errors found by `@google/repo check`

docs: replace google/ with googleapis/ in URIs

---

synth.py

Do not generate libraries with synth

---

samples/drive/download.js
samples/drive/upload.js

process.stdout.clearLine is not a function, use readline

fix(tests): Fix samples test

---

src/generator/templates/api-endpoint.njk
src/generator/templates/resource-partial.njk

Fixes #1374  (it's a good idea to open an issue first for discussion)

Fix for #1374 Generator missing standard parameters

---

src/generator/templates/api-endpoint.njk
src/generator/templates/resource-partial.njk

Fixes #1266  Adds support for repeated fields

feat: Add support for repeated fields

---

samples/drive/README.md

Added information to run the quickstart sample

---

samples/oauth2.js
samples/sampleclient.js

fix(samples): fix url parsing in sampleClient

---

.compodocrc
README.md
package.json
src/generator/docs.ts
src/generator/templates/index.html.njk

Prototype available at https://apis-nodejs.firebaseapp.com/.
Fixes #1489 
Fixes #1332 
Fixes #1294
Fixes #1261

docs: fix the doc generator

---

README.md

Makes the service account sample include setup to be more similar to other samples.
Try running the sample yourself.

docs: improve the compute sample in the README

---

src/generator/templates/method-partial.njk
src/generator/templates/resource-partial.njk

Some APIs now contain dashes in method names ([example](https://container.googleapis.com/$discovery/rest?version=v1)). Fixing that by changing all method names to camelCase.

fix: convert method names to camelCase

---

src/generator/generator.ts
src/generator/templates/README.md.njk
src/generator/templates/api-endpoint.njk
src/generator/templates/api-index.njk
src/generator/templates/index.njk
src/generator/templates/package.json.njk
src/generator/templates/root-index.njk
src/generator/templates/webpack.config.js.njk

Generating small packages that are:
- webpackable
- usable (`AuthPlus` is re-exported from `googleapis-common` to make it available for users).

feat: generating webpackable packages

---

samples/people/me.js

The plus API is being deprecated. This updates the sample code to use the people API instead.
Fixes #1600.

Use people API instead of plus API

---

CONTRIBUTING.md

Why?
- Link does not exist.
- Releasing shouldn't be done by contributors anyways.

docs: Remove "releasing" ToC from CONTRIBUTING.md

---

src/apis/bigquery/v2.ts
src/apis/cloudbilling/v1.ts
src/apis/cloudfunctions/v1.ts
src/apis/cloudsearch/v1.ts
src/apis/composer/v1beta1.ts
src/apis/containeranalysis/v1alpha1.ts
src/apis/dns/v1.ts
src/apis/dns/v2beta1.ts
src/apis/drive/v2.ts
src/apis/drive/v3.ts
src/apis/fitness/v1.ts
src/apis/iam/v1.ts
src/apis/ml/v1.ts
src/apis/monitoring/v3.ts
src/apis/people/v1.ts
src/apis/remotebuildexecution/v1.ts
src/apis/remotebuildexecution/v1alpha.ts
src/apis/remotebuildexecution/v2.ts
src/apis/servicemanagement/v1.ts
src/apis/servicenetworking/index.ts
src/apis/servicenetworking/v1.ts
src/apis/vault/v1.ts
src/index.ts

feat: run the generator

---

samples/drive/download.js

Refs #1651 just a thought, based on the conversation in `1651` it might be worth adding this point of clarification in our sample.

docs: document export as alternative to get

---

README.md

Minor: Simplify README wording.
- Dedupe API Explorer link
- Don't use `here`. Bad SEO and link usage.

docs: Don't repeat ourselves with the API list

---

README.md
samples/drive/export.js
test/samples/test.samples.drive.ts

Fixes https://github.com/googleapis/gaxios/issues/58

docs: update docs and samples for drive export

---

package.json
test/samples/test.compute.samples.ts

The most important update in this PR is the introduction of a patched version of `gts` which does not run out of memory when processing a large number of files (I believe `gts` might be why a variety of builds were timing out).

fix(deps): pull in version of gts that does not OOM error

---

README.md

docs: remove reference to createScopedRequired

---

README.md
samples/blogger/blogger.js

fix(docs): bloggerId should be a string

---

.github/publish.yml

let's see if the 9 minute timeout in a cloud function is enough for library publications of google-api-nodejs-client, this would make me confident that we can move to a GitHub app for all of our publications.

build: switch to GitHub app for publish

---

system-test/kitchen.test.ts

`should be able to use the d.ts` occasionally times out, let's start by retrying it.

test: the kitchen sink system test sometimes times out

---

test/fixtures/discovery/blogger.json
test/fixtures/discovery/drive.json
test/test.apikey.ts
test/test.auth.ts
test/utils.ts

rather than loading discover docs over the wire, which has been proving flaky (I believe turning net connect on and off is the source of the flakes in #2036), use nock to load discovery docs from a fixture.
fixes: #2036, #2035

test: use discovery docs from fixture

---

samples/drive/README.md

I was going through the example for google drive and came across the README, where I was told to create `oauth2.keys.json`.  What wasn't immediately clear was that everything needed to be nested under a key of `web`, [as shown here](https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/drive/quickstart.js#L29). A specific example would have been really helpful, so I added a quick one.

docs: update readme for drive readme

---

src/generator/download.ts
test/test.download.ts
test/test.samplegen.ts

This change ignores updates to the `discovery` directory if they only contain changes to the `revision` or `etag` fields.  It will reduce the noisiness of re-generation after introducing the discovery caching feature.
One important side effect of this change - as it's written here, *APIs that have been removed from the discovery index will not be automatically cleaned up*.  This is consistent with the approach taken by Go.  I'm on the fence 50/50 if it's a good idea to be honest.  The big benefit I see here is that maybe (just maybe) we can avoid bumping the semver major every time we want to ship.  The downside is that we will never really prune missing APIs.  I can go back and add the code to do the cleanup if folks thing it's advisable.

build: ignore revision-only updates

---

src/googleapis.ts
test/test.apikey.ts
test/test.auth.ts
test/test.clients.ts
test/test.discover.ts
test/test.drive.v2.ts
test/test.media.ts
test/test.options.ts
test/test.path.ts
test/test.query.ts
test/test.synth.ts
test/test.transporters.ts
test/utils.ts

I suggest disabling whitespace for this review.  This attempts to remove all instances of `nock.enableNetworkAccess`, and use mocking with local discovery files for all unit tests.  There's one place where this isn't possible, but the code is otherwise entirely covered.

refactor: do not require network access for unit tests

---

.github/workflows/generator.yaml
src/generator/synth.ts

Getting the GitHub Action for our cron right has been a bit of a struggle that involves waiting 24 hours and hoping for the best.  This change attempts to fix the current glitch, but adds a repository dispatch hook so a well crafted post with the appropriate auth token can trigger the job.  Firing it looks like this:
https://developer.github.com/v3/repos/#create-a-repository-dispatch-event

build: add repository dispatch trigger

---

samples/accessTokenAuth.js
samples/package.json
samples/test/test.samples.auth.js

Someone was looking for how to do auth with an access token over here:
https://github.com/googleapis/google-api-nodejs-client/issues/1973
Half to have a sample, and half to make sure my answer was going to work, added this :)

docs: add a sample of using access token auth
